import type { CollectionConfig } from 'payload'

export const CalculatorSubmissions: CollectionConfig = {
  slug: 'calculator-submissions',
  labels: { singular: 'Calculator Submission', plural: 'Calculator Submissions' },
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'phone', 'totalWattage', 'recommendedKit', 'createdAt'],
    description: 'Quotations generated by users on the solar calculator.',
  },
  access: {
    read: ({ req }) => Boolean(req.user),
    create: () => true,
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user),
  },
  fields: [
    { name: 'name', type: 'text', required: true },
    { name: 'phone', type: 'text', required: true },
    { name: 'email', type: 'email' },
    { name: 'location', type: 'text', admin: { description: 'City / town' } },
    {
      name: 'appliances',
      type: 'array',
      required: true,
      labels: { singular: 'Appliance', plural: 'Appliances' },
      fields: [
        { name: 'name', type: 'text', required: true },
        { name: 'wattage', type: 'number', required: true, min: 0 },
        { name: 'quantity', type: 'number', defaultValue: 1, min: 1 },
        { name: 'hoursPerDay', type: 'number', defaultValue: 4, min: 0 },
      ],
    },
    {
      name: 'totalWattage',
      type: 'number',
      admin: { description: 'Sum of (wattage × quantity)' },
    },
    {
      name: 'dailyEnergyWh',
      type: 'number',
      admin: { description: 'Sum of (wattage × quantity × hoursPerDay)' },
    },
    {
      name: 'recommendedKit',
      type: 'relationship',
      relationTo: 'products',
      admin: { description: 'Optional: kit assigned by sales after review' },
    },
    {
      name: 'recommendation',
      type: 'group',
      admin: { description: 'Auto-generated kit suggestion (server-side)' },
      fields: [
        { name: 'panelWattsTotal', type: 'number' },
        { name: 'inverterWatts', type: 'number' },
        { name: 'batteryWh', type: 'number' },
        { name: 'estimatedPriceKes', type: 'number' },
        { name: 'notes', type: 'textarea' },
      ],
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'new',
      options: [
        { label: 'New', value: 'new' },
        { label: 'Contacted', value: 'contacted' },
        { label: 'Quoted', value: 'quoted' },
        { label: 'Won', value: 'won' },
        { label: 'Lost', value: 'lost' },
      ],
    },
  ],
}
